version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

parameters:
  jdk-image:
    type: string
    default: cimg/openjdk:21.0.0

jobs:
  test:
    environment:
      MAVEN_OPTS: -Xmx3200m
    docker:
      - image: << pipeline.parameters.jdk-image >>
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - spring-search-{{ checksum "pom.xml" }}
            - spring-search-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spring-search-{{ checksum "pom.xml" }}
      - run: mvn test
      - store_artifacts:
          path:  ~/project/target/test-results
      - codecov/upload:
          file: ~/project/target/test-results/coverage/jacoco/jacoco.xml
          flags: coverage
          upload_name: Coverage

workflows:
  version: 2
  test:
    jobs:
      - test