name: Test & Coverage
on:
  pull_request:
    branches:
      - '*'

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up the Maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn --batch-mode --update-snapshots verify -Dgpg.skip=true -Ddependency-check.skip=true

      - name: Add coverage
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/target/test-results/coverage/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '### :zap: Coverage report'
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 75
          continue-on-error: false
